export const FIELDS_FETCHING = 'FIELDS_FETCHING';
export const FIELDS_FETCH_COMPLETE = 'FIELDS_FETCH_COMPLETE';

export const FIELD_ADDING = 'FIELD_ADDING';
export const FIELD_ADDED  = 'FIELD_ADDED';

export const FIELD_DELETEING = 'FIELD_DELETEING';
export const FIELD_DELETE_COMPLETED = 'FIELD_DELETED'

export const FIELD_UPDATING = 'FIELD_UPDATING';
export const FIELD_UPDATE_COMPLETED = 'FIELD_UPDATE_COMPLETED';

export const FIELD_SELECT = 'FIELD_SELECT';
