<<<<<<< HEAD
export const UPDATE_USER_FORMS = 'UPDATE_USER_FORMS';
export const DELETE_USER_FORMS = 'DELETE_USER_FORMS';
=======
export const SET_USER_NAME = 'SET_USER_NAME';
export const USER_START_AUTHORIZING = 'USER_START_AUTHORIZING';
export const USER_AUTHORIZED = 'USER_AUTHORIZED';
>>>>>>> 22b3ffb0f696cc9989cc0fc3e526d42ef0807e65
