export const FETCH_FORMS = 'FETCH_FORMS';
export const FORMS_FETCHING = 'FORMS_FETCHING';
export const FORMS_FETCH_COMPLETE = 'FORMS_FETCH_COMPLETE';
export const FORMS_FETCH_ERROR = 'FORMS_FETCH_ERROR';

export const CREATE_FORM = 'CREATE_FORM';
export const CREATING_FORM = 'CREATING_FORM';
export const FORM_CREATED = 'FORM_CREATED';

export const DELETEING_FORM = 'DELETEING_FORM';
export const FORM_DELETE_COMPLETE  = 'FORM_DELETE_COMPLETE'; 


export const SELECT_FORM = 'SELECT_FORM';
